import requests
import json
from pathlib import Path
ROOT = str(Path(__file__).resolve().parent)
# Negative_prompt="low res, bad anatomy, bad hands, text, error, missing fingers, wrong fingers, extra digit ,fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, bad feet"
# Negative_prompt="lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry"
# STEP=32
# SFG_SCALE=12



def get_config():
    path=ROOT+"/config.json"
    with open(path,encoding='UTF-8') as f:
        data = json.load(f)
    return data



def tags_paint(tags,huge=False):
    config=get_config()
    tags= tags +"," + config["postive"]
    if huge:
        size=config["huge_size"]
    else:
        size=config["size"]
    data='{"fn_index":11,"data":["'+tags+'","'+config["negative"]+'","None","None",'+str(config["step"])+',"Euler a",true,false,1,1,'+str(config["sfg_scale"])+',-1,-1,0,0,0,false,'+str(size)+','+str(size)+',false,false,0.7,"None",false,false,null,"","Seed","","Steps","",true,false,null,"{\\"prompt\\": \\"extremely detailed CG unity 8k wallpaper\\", \\"all_prompts\\": [\\"extremely detailed CG unity 8k wallpaper\\"], \\"negative_prompt\\": \\"lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry\\", \\"seed\\": 2760208798, \\"all_seeds\\": [2760208798], \\"subseed\\": 1461866167, \\"all_subseeds\\": [1461866167], \\"subseed_strength\\": 0, \\"width\\": 512, \\"height\\": 512, \\"sampler_index\\": 0, \\"sampler\\": \\"Euler a\\", \\"cfg_scale\\": 12, \\"steps\\": 35, \\"batch_size\\": 1, \\"restore_faces\\": false, \\"face_restoration_model\\": null, \\"sd_model_hash\\": \\"925997e9\\", \\"seed_resize_from_w\\": 0, \\"seed_resize_from_h\\": 0, \\"denoising_strength\\": null, \\"extra_generation_params\\": {}, \\"index_of_first_image\\": 0, \\"infotexts\\": [\\"extremely detailed CG unity 8k wallpaper\\\\nNegative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry\\\\nSteps: 35, Sampler: Euler a, CFG scale: 12, Seed: 2760208798, Size: 512x512, Model hash: 925997e9\\"], \\"styles\\": [\\"None\\", \\"None\\"], \\"job_timestamp\\": \\"20221009173044\\"}","<p>extremely detailed CG unity 8k wallpaper<br>\\nNegative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry<br>\\nSteps: 35, Sampler: Euler a, CFG scale: 12, Seed: 2760208798, Size: 512x512, Model hash: 925997e9</p><div class=\'performance\'><p class=\'time\'>Time taken: <wbr>7.51s</p><p class=\'vram\'>Torch active/reserved: 3632/3970 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"],"session_hash":"pcztlkikk5a"}'

    data=data.encode("utf-8")
    res=requests.post(url="http://127.0.0.1:7860/api/predict/",data=data)
    temp=str(res.content,'utf-8')

    result=json.loads(temp)
    img=result["data"][0][0]
    img=img.replace("data:image/png;base64,","")
    img=img.encode('utf-8')
    return img

def pic_paint(tags,pic,huge=False):
    config = get_config()
    tags = tags + "," + config["postive"]
    if huge:
        size = config["huge_size"]
    else:
        size = config["size"]
    # data='{"fn_index":29,"data":[0,"'+tags+'","'+config["negative"]+'","None","None","data:image/png;base64,'+pic+'",null,null,null,"Draw mask",'+str(config["step"])+',"Euler a",4,"original",false,false,1,1,'+str(config["sfg_scale"])+',0.75,-1,-1,0,0,0,false,'+str(size)+','+str(size)+',"Just resize",false,32,"Inpaint masked","","","None","","",1,50,0,false,4,1,"<p style=\\"margin-bottom:0.75em\\">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>",128,8,["left","right","up","down"],1,0.05,128,4,"fill",["left","right","up","down"],false,false,null,"","<p style=\\"margin-bottom:0.75em\\">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>",64,"None","Seed","","Steps","",true,false,null,"{\\"prompt\\": \\"\\", \\"all_prompts\\": [\\"\\"], \\"negative_prompt\\": \\"\\", \\"seed\\": 2722034463, \\"all_seeds\\": [2722034463], \\"subseed\\": 1176374452, \\"all_subseeds\\": [1176374452], \\"subseed_strength\\": 0, \\"width\\": 512, \\"height\\": 512, \\"sampler_index\\": 0, \\"sampler\\": \\"Euler a\\", \\"cfg_scale\\": 7, \\"steps\\": 20, \\"batch_size\\": 1, \\"restore_faces\\": false, \\"face_restoration_model\\": null, \\"sd_model_hash\\": \\"925997e9\\", \\"seed_resize_from_w\\": 0, \\"seed_resize_from_h\\": 0, \\"denoising_strength\\": 0.75, \\"extra_generation_params\\": {\\"Mask blur\\": 4}, \\"index_of_first_image\\": 0, \\"infotexts\\": [\\"squid\\\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2722034463, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4\\"], \\"styles\\": [\\"None\\", \\"None\\"], \\"job_timestamp\\": \\"20221008213258\\"}","<p>squid<br>\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2722034463, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4</p><div class=\'performance\'><p class=\'time\'>Time taken: <wbr>3.82s</p><p class=\'vram\'>Torch active/reserved: 3619/4232 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"],"session_hash":"uorg3j8f4"}'
    data='{"fn_index":31,"data":[0,"'+tags+'","'+config["negative"]+'","None","None","data:image/png;base64,'+pic+'",null,null,null,"Draw mask",'+str(config["step"])+',"Euler a",4,"original",true,false,1,1,'+str(config["sfg_scale"])+',0.75,-1,-1,0,0,0,false,'+str(size)+','+str(size)+',"Just resize",false,32,"Inpaint masked","","","None","","",1,50,0,false,4,1,"<p style=\\"margin-bottom:0.75em\\">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>",128,8,["left","right","up","down"],1,0.05,128,4,"fill",["left","right","up","down"],false,false,null,"","<p style=\\"margin-bottom:0.75em\\">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>",64,"None","Seed","","Steps","",true,false,null,"{\\"prompt\\": \\"happy\\", \\"all_prompts\\": [\\"happy\\"], \\"negative_prompt\\": \\"\\", \\"seed\\": 2752536185, \\"all_seeds\\": [2752536185], \\"subseed\\": 381692584, \\"all_subseeds\\": [381692584], \\"subseed_strength\\": 0, \\"width\\": 512, \\"height\\": 512, \\"sampler_index\\": 0, \\"sampler\\": \\"Euler a\\", \\"cfg_scale\\": 7, \\"steps\\": 20, \\"batch_size\\": 1, \\"restore_faces\\": false, \\"face_restoration_model\\": null, \\"sd_model_hash\\": \\"925997e9\\", \\"seed_resize_from_w\\": 0, \\"seed_resize_from_h\\": 0, \\"denoising_strength\\": 0.75, \\"extra_generation_params\\": {\\"Mask blur\\": 4}, \\"index_of_first_image\\": 0, \\"infotexts\\": [\\"happy\\\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2752536185, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Eta: 0.67, Clip skip: 2, Mask blur: 4\\"], \\"styles\\": [\\"None\\", \\"None\\"], \\"job_timestamp\\": \\"20221009224643\\", \\"clip_skip\\": 2}","<p>happy<br>\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2752536185, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Eta: 0.67, Clip skip: 2, Mask blur: 4</p><div class=\'performance\'><p class=\'time\'>Time taken: <wbr>3.46s</p><p class=\'vram\'>Torch active/reserved: 3619/4232 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"],"session_hash":"ktadofe9vzo"}'
    # data='{"data":[["data:image/png;base64,'+pic+'"],"{\\"prompt\\": \\"'+tags+'\\", \\"all_prompts\\": [\\"squid\\"], \\"negative_prompt\\": \\"'+Negative_prompt+'\\", \\"seed\\": 1184675618, \\"all_seeds\\": [1184675618], \\"subseed\\": 2524884941, \\"all_subseeds\\": [2524884941], \\"subseed_strength\\": 0, \\"width\\": 512, \\"height\\": 512, \\"sampler_index\\": 0, \\"sampler\\": \\"Euler a\\", \\"cfg_scale\\": 7, \\"steps\\": 20, \\"batch_size\\": 1, \\"restore_faces\\": false, \\"face_restoration_model\\": null, \\"sd_model_hash\\": \\"925997e9\\", \\"seed_resize_from_w\\": 0, \\"seed_resize_from_h\\": 0, \\"denoising_strength\\": 0.75, \\"extra_generation_params\\": {\\"Mask blur\\": 4}, \\"index_of_first_image\\": 0, \\"infotexts\\": [\\"squid\\\\nNegative prompt: lowres, bad anatomy, bad hands, text,error, missing fngers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet\\\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1184675618, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4\\"], \\"styles\\": [\\"None\\", \\"None\\"], \\"job_timestamp\\": \\"20221008212102\\"}","<p>squid<br>\\nNegative prompt: lowres, bad anatomy, bad hands, text,error, missing fngers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet<br>\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1184675618, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4</p><div class=\'performance\'><p class=\'time\'>Time taken: <wbr>3.71s</p><p class=\'vram\'>Torch active/reserved: 3619/4232 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"],"is_generating":false,"duration":3.71005916595459,"average_duration":3.8401403196396364}'
    # data='{"fn_index":29,"data":[0,"'+tags+'","'+config["negative"]+'","None","None","data:image/png;base64,'+pic+'",null,null,null,"Draw mask",'+str(config["step"])+',"Euler a",4,"original",false,false,1,1,'+str(config["sfg_scale"])+',0.75,-1,-1,0,0,0,false,'+str(size)+','+str(size)+',"Just resize",false,32,"Inpaint masked","","","None","","",1,50,0,false,4,1,"<p style=\\"margin-bottom:0.75em\\">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>",128,8,["left","right","up","down"],1,0.05,128,4,"fill",["left","right","up","down"],false,false,null,"","<p style=\\"margin-bottom:0.75em\\">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>",64,"None","Seed","","Steps","",true,false,null,"",""],"session_hash":"pcztlkikk5a"}'
    data = data.encode("utf-8")
    res=requests.post(url="http://127.0.0.1:7860/api/predict/.",data=data)

    temp=str(res.content,'utf-8')
    result=json.loads(temp)
    img=result["data"][0][0]
    img=img.replace("data:image/png;base64,","")
    img=img.encode('utf-8')
    return img
# def tags_paint_2(tags):
#     data='{"fn_index":11,"data":["'+tags+'","'+Negative_prompt+'","None","None",25,"Euler a",false,false,1,1,7,-1,-1,0,0,0,false,640,640,false,false,0.7,"None",false,false,null,"","Seed","","Steps","",true,false,null,"{\\"prompt\\": \\"chinese emoticon\\", \\"all_prompts\\": [\\"chinese emoticon\\"], \\"negative_prompt\\": \\"lowres, bad anatomy, bad hands, text,error, missing fingers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet\\", \\"seed\\": 3266417791, \\"all_seeds\\": [3266417791], \\"subseed\\": 3439157180, \\"all_subseeds\\": [3439157180], \\"subseed_strength\\": 0, \\"width\\": 512, \\"height\\": 512, \\"sampler_index\\": 0, \\"sampler\\": \\"Euler a\\", \\"cfg_scale\\": 7, \\"steps\\": 20, \\"batch_size\\": 1, \\"restore_faces\\": false, \\"face_restoration_model\\": null, \\"sd_model_hash\\": \\"925997e9\\", \\"seed_resize_from_w\\": 0, \\"seed_resize_from_h\\": 0, \\"denoising_strength\\": null, \\"extra_generation_params\\": {}, \\"index_of_first_image\\": 0, \\"infotexts\\": [\\"chinese emoticon\\\\nNegative prompt: lowres, bad anatomy, bad hands, text,error, missing fingers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet\\\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3266417791, Size: 512x512, Model hash: 925997e9\\"], \\"styles\\": [\\"None\\", \\"None\\"], \\"job_timestamp\\": \\"20221008155749\\"}","<p>chinese emoticon<br>\\nNegative prompt: lowres, bad anatomy, bad hands, text,error, missing fingers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet<br>\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3266417791, Size: 512x512, Model hash: 925997e9</p><div class=\'performance\'><p class=\'time\'>Time taken: <wbr>4.29s</p><p class=\'vram\'>Torch active/reserved: 3653/4228 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"],"session_hash":"rileq0pav9m"}'
#
#     data=data.encode("utf-8")
#     res=requests.post(url="http://127.0.0.1:7861/api/predict/",data=data)
#     temp=str(res.content,'utf-8')
#     print(temp)
#     result=json.loads(temp)
#     img=result["data"][0][0]
#     img=img.replace("data:image/png;base64,","")
#     img=img.encode('utf-8')
#     return img


def pic_paint_2(tags,pic):
    # data='{"data":[["data:image/png;base64,'+pic+'"],"{\\"prompt\\": \\"'+tags+'\\", \\"all_prompts\\": [\\"squid\\"], \\"negative_prompt\\": \\"'+Negative_prompt+'\\", \\"seed\\": 1184675618, \\"all_seeds\\": [1184675618], \\"subseed\\": 2524884941, \\"all_subseeds\\": [2524884941], \\"subseed_strength\\": 0, \\"width\\": 512, \\"height\\": 512, \\"sampler_index\\": 0, \\"sampler\\": \\"Euler a\\", \\"cfg_scale\\": 7, \\"steps\\": 20, \\"batch_size\\": 1, \\"restore_faces\\": false, \\"face_restoration_model\\": null, \\"sd_model_hash\\": \\"925997e9\\", \\"seed_resize_from_w\\": 0, \\"seed_resize_from_h\\": 0, \\"denoising_strength\\": 0.75, \\"extra_generation_params\\": {\\"Mask blur\\": 4}, \\"index_of_first_image\\": 0, \\"infotexts\\": [\\"squid\\\\nNegative prompt: lowres, bad anatomy, bad hands, text,error, missing fngers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet\\\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1184675618, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4\\"], \\"styles\\": [\\"None\\", \\"None\\"], \\"job_timestamp\\": \\"20221008212102\\"}","<p>squid<br>\\nNegative prompt: lowres, bad anatomy, bad hands, text,error, missing fngers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet<br>\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1184675618, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4</p><div class=\'performance\'><p class=\'time\'>Time taken: <wbr>3.71s</p><p class=\'vram\'>Torch active/reserved: 3619/4232 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"],"is_generating":false,"duration":3.71005916595459,"average_duration":3.8401403196396364}'
    data='{"fn_index":29,"data":[0,"'+tags+'","","None","None","data:image/png;base64,'+pic+'",null,null,null,"Draw mask",20,"Euler a",4,"original",false,false,1,1,7,0.75,-1,-1,0,0,0,false,512,512,"Just resize",false,32,"Inpaint masked","","","None","","",1,50,0,false,4,1,"<p style=\\"margin-bottom:0.75em\\">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>",128,8,["left","right","up","down"],1,0.05,128,4,"fill",["left","right","up","down"],false,false,null,"","<p style=\\"margin-bottom:0.75em\\">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>",64,"None","Seed","","Steps","",true,false,null,"{\\"prompt\\": \\"squid\\", \\"all_prompts\\": [\\"squid\\"], \\"negative_prompt\\": \\"\\", \\"seed\\": 2722034463, \\"all_seeds\\": [2722034463], \\"subseed\\": 1176374452, \\"all_subseeds\\": [1176374452], \\"subseed_strength\\": 0, \\"width\\": 512, \\"height\\": 512, \\"sampler_index\\": 0, \\"sampler\\": \\"Euler a\\", \\"cfg_scale\\": 7, \\"steps\\": 20, \\"batch_size\\": 1, \\"restore_faces\\": false, \\"face_restoration_model\\": null, \\"sd_model_hash\\": \\"925997e9\\", \\"seed_resize_from_w\\": 0, \\"seed_resize_from_h\\": 0, \\"denoising_strength\\": 0.75, \\"extra_generation_params\\": {\\"Mask blur\\": 4}, \\"index_of_first_image\\": 0, \\"infotexts\\": [\\"squid\\\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2722034463, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4\\"], \\"styles\\": [\\"None\\", \\"None\\"], \\"job_timestamp\\": \\"20221008213258\\"}","<p>squid<br>\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2722034463, Size: 512x512, Model hash: 925997e9, Denoising strength: 0.75, Mask blur: 4</p><div class=\'performance\'><p class=\'time\'>Time taken: <wbr>3.82s</p><p class=\'vram\'>Torch active/reserved: 3619/4232 MiB, <wbr>Sys VRAM: 6144/6144 MiB (100.0%)</p></div>"],"session_hash":"uorg3j8f4"}'
    data = data.encode("utf-8")
    res=requests.post(url="http://127.0.0.1:7861/api/predict/.",data=data)

    temp=str(res.content,'utf-8')
    result=json.loads(temp)

    img=result["data"][0][0]
    img=img.replace("data:image/png;base64,","")
    img=img.encode('utf-8')
    return img

# pic_paint("squid","iVBORw0KGgoAAAANSUhEUgAAADEAAABCCAYAAAD+Kj5zAAAAZ0lEQVRoge3PAQ3AIADAMMC/Z0DEE/akVbDNfY2fW68DvmCiwkSFiQoTFSYqTFSYqDBRYaLCRIWJChMVJipMVJioMFFhosJEhYkKExUmKkxUmKgwUWGiwkSFiQoTFSYqTFSYqDBRcQCqWQSAaGD7+gAAAABJRU5ErkJggg==")